limit_req_zone $binary_remote_addr$host zone=low_req:5m rate=10r/s;
limit_conn_zone $binary_remote_addr$host zone=low_conn:5m;

limit_req zone=low_req burst=20 nodelay;
limit_req_status 429;
limit_req_log_level warn;

limit_conn low_conn 5;
limit_conn_status 429;
limit_conn_log_level warn;