server {
    listen 443 ssl;
    server_name qr.vlad-dev.ru www.qr.vlad-dev.ru;

    location / {
        limit_except GET {
            deny all;
        }
        proxy_pass http://qr-scanner:3000/;
    }
}