server {
    listen 443 ssl;
    server_name cats.vlad-dev.ru www.cats.vlad-dev.ru;

    location / {
        limit_except GET {
            deny all;
        }
        proxy_pass http://cats-app:3000/;
    }
}